In [1]:
pip install numpy


In [2]:
import numpy as np

In [6]:
arr = np.array([30,40,60])
print(arr)
type(arr)

[30 40 60]


numpy.ndarray

In [5]:
list1 = [10,20,30,40]
print(list1)
print(type(list1))

[10, 20, 30, 40]
<class 'list'>


# Types of Array :

## One Dimensional Array :


In [9]:
arr = np.array([10,20,30])
print(arr)

[10 20 30]


In [8]:
arr.ndim

1

## Two Dimensional Array :

In [10]:
arr = np.array([[10,20,30],[40,50,60]])
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [11]:
arr.ndim

2

## Three Dimensional Array :

In [14]:
arr = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
arr

array([[[10, 20],
        [30, 40]],

       [[50, 60],
        [70, 80]]])

In [15]:
arr.ndim

3

## Basic Operations :

    ndim
    dtype
    size
    shape

In [16]:
# Dtype :
a = np.array([1,2,3])
b = np.array([4.2,5.8,9.4])
c = np.array(['arun','meena','arvind'])

print("a dtype : ",a.dtype)
print("b dtype : ",b.dtype)
print("c dtype : ",c.dtype)

a dtype :  int32
b dtype :  float64
c dtype :  <U6


In [20]:
# Size :

x = np.array([["apple","orange"],["Mango","Papaya"],["banana","cherry"]])
print("Size of X : ",x.size)

Size of X :  6


In [24]:
# Shape :

a = np.array([[1,2,3],[7,8,9],[4,5,6]])
print(a)
print("Shape of a : ",a.shape)

[[1 2 3]
 [7 8 9]
 [4 5 6]]
Shape of a :  (3, 3)


## Creating Arrays :


In [1]:
import numpy as np

In [4]:
arr = np.array([30])
arr

array([30])

In [5]:
arr.ndim

1

## Multi or Higher Dimensional Array 

**ndmin** - *minimmum number of dimensions*

it is an argument we pass in *np.array()* function to force the array have a minimum number of dimensions,even if the original data is smaller
it won't **reduce** exisiting dimensions if you pass already a higher dimensional array.

In [6]:
arr = np.array([20,30,40],ndmin = 5)
arr

array([[[[[20, 30, 40]]]]])

In [7]:
arr.ndim

5

## Array Indexing :

### One Dimensional Array :

    # syntax :-> array[index]

In [14]:
arr = np.array(['apple','orange','mango','banana'])
arr[-4:-1]

array(['apple', 'orange', 'mango'], dtype='<U6')

In [15]:
arr[0] + arr[-1]

'applebanana'

## Two Dimensional Array :

In [16]:
# Two Dimensional Array :

"""
Syntax :
    array[row_index,column_index]
"""

arr = np.array([[10,20,30,40],[50,60,70,80]])
arr

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [19]:
arr[1,3]

80

In [22]:
arr[:,1:3]

array([[20, 30],
       [60, 70]])

## Thre Dimensional Array :

In [23]:
# Three Dimensional Array :
"""
array[layer,row,column]
"""

arr = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])

print(arr)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [27]:
arr[1,0,1]

60

In [29]:
arr[:,1,:]

array([[30, 40],
       [70, 80]])

## Negative Indexing :

In [30]:
# One Dimensional Array :

arr = np.array([10,20,30,40,50])

print("Last element : ",arr[-1])
print("second Last element : ",arr[-2])

Last element :  50
second Last element :  40


In [32]:
# Two Dimensional Array :

arr = np.array([[10,20,30],[40,50,60]])
arr
# print("Last Row : ",arr[-1])
# print("Last Element of Last Row : ",arr[-1][-1])
# print("Last column first row : ",arr[-2][-1])

array([[10, 20, 30],
       [40, 50, 60]])

In [35]:
arr[-1,-2:]

array([50, 60])

# Array Slicing :

**syntax :**

    array[start,end,step]


In [36]:
# Positive Index
arr = np.array([10,20,30,40,50,60])
print(arr[0:3])
print(arr[:5])
print(arr[2:])
print(arr[::2])


[10 20 30]
[10 20 30 40 50]
[30 40 50 60]
[10 30 50]


In [37]:
# Negative Index :

arr = np.array([10,20,30,40,50,60])

# [30 40 50]
# [40 50 60]
# [10 20 30]
# full reverse

print(arr[-4:-1])
print(arr[-3:])
print(arr[:-3])

print(arr[::-1])

[30 40 50]
[40 50 60]
[10 20 30]
[60 50 40 30 20 10]


In [38]:
# Two Dimensional :

# arr[row_index, column_index]

arr = np.array([[1,2,3],
       [4,5,6],
       [7,8,9]])
print(arr)
       

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
arr = np.array([
       [1,2,3],
       [4,5,6],
       [7,8,9]])

# [[2 3],[5 6]]
# [1,4,7]
# [4,5,6]

print(arr[0:2, 1:])

print(arr[0: ,0])

print(arr[1, 0:])

[[2 3]
 [5 6]]
[1 4 7]
[4 5 6]


In [40]:
# 2D Negative Inedx :

arr = np.array([
       [1,2,3],
       [4,5,6],
       [7,8,9]])

# [[5,6],[8,9]]
# [3,6,9]
# [7,8,9]

print(arr[-2: ,-2:])

print(arr[:,-1])

print(arr[-1 , :])

[[5 6]
 [8 9]]
[3 6 9]
[7 8 9]


# Data types in Numpy :

Integer - **i**  - Signed integer

Unsinged Integer - **u** - only positive integers

float  - **f**  - Decimal numbers

complex float - **c**  - complex numbers

boolean -  **b** - True or False

string  - **S** - ASCII string

unicode string  - **U** - international text

object  - **O**  - Python objects

datetime - **M**  - date & time 

timedelta - **m** - Time duration(diff between two dates)

void   -  **V** - Raw memory block


In [41]:
print(np.array([1],dtype='i4'))
print(np.array([1+2j], dtype='c8'))
print(np.array([4.567],dtype = 'f4'))
print(np.array(["வணக்கம்"],dtype = 'U8'))


[1]
[1.+2.j]
[4.567]
['வணக்கம்']


## How to check dtype Character :

In [42]:
arr = np.array(["3.7"])

print(arr.dtype)

<U3


In [43]:
arr.dtype.char

'U'

# View & Copy :

### View :

- a **view** is just another way of looking at the same data
- it does not create a new copy of the array in memory.

**Syntax :**

view_array = original_array.view()

### Copy :

- a **copy** is a new array created from the original.
- Changing the copy won't affect the original array.

**Syntax :**

copy_array = original_array.copy()
    

In [44]:
# View :

arr = np.array([10,20,30])

arr

array([10, 20, 30])

In [46]:
v = arr.view()

v[0]

10

In [49]:
v[0] = 999
arr[1] = 199

print("array",arr)
print("view",v)

array [999 199  30]
view [999 199  30]


In [51]:
# Copy :

arr = np.array(["apple","orange","mango"])

c = arr.copy()

c[0] = "Lion"

print(arr)
print(c)

['apple' 'orange' 'mango']
['Lion' 'orange' 'mango']


In [52]:
# Default behaviour with slicing :

a = np.array([10,20,30,40])

b = a[1:3]
a

array([10, 20, 30, 40])

In [53]:
b

array([20, 30])

In [57]:

b[0] = 999
b
a

array([ 10, 999,  30,  40])

In [58]:

c = a[1:3].copy()
c

array([999,  30])

In [60]:
c[0] = 99

print(a)
# print(b)
print(c)

[ 10 999  30  40]
[99 30]


In [61]:
# To Check memory is shared?

print(np.shares_memory(a,b))

print(np.shares_memory(a,c))

# b.base is a
# c.base is a

True
False


# Shape :

**shape** is a property of a numpy array that returns a tuple representing the dimensions of the array.

#### Syntax :

array.shape

**[rows,cols,depth]**

In [62]:
# Example :

arr = np.array([10, 20, 30])
print(arr.shape) 

# o/p --> Meaning 1D array with 3 elements

(3,)


In [63]:
# 2D Array :

arr = np.array([[1,2,3],[20,30,40]])
arr

array([[ 1,  2,  3],
       [20, 30, 40]])

In [64]:

print(arr.shape) # -> 2 rows 3 columns

(2, 3)


In [67]:
# 3D Array :

arr = np.array([
    [
        [10,20],
        [30,40]
    ],
    [
        [50,60],
        [70,80]
    ],
    [
        [90,100],
        [25,35]
    ]
])

arr

array([[[ 10,  20],
        [ 30,  40]],

       [[ 50,  60],
        [ 70,  80]],

       [[ 90, 100],
        [ 25,  35]]])

In [69]:

print(arr.shape) # --> 3 Blocks -> each block has 2 rows * 2 cols

(3, 2, 2)


## Reshape :

**reshape** is a method that changes the shape of an array without changing its data
original data will be reorganized into a new shape 
only if total number of elements is the same

#### Syntax :

array.reshape(new_shape)

array.reshape(rows,cols)

array.reshape(-1,n) --> Auto Calculation

In [70]:
# Example :

a = np.array([1,2,3,4,5,6])

print(a)
print(a.shape)
print("\n------------\n")


[1 2 3 4 5 6]
(6,)

------------



In [74]:

b = a.reshape(6,1)
print(b)
print(b.shape)
print(a)

print(np.shares_memory(a,b))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)
[1 2 3 4 5 6]
True


## -1 in reshape() :

    when you use -1 inside the reshape() method, it automatically calculates the appropriate dimension size for you based on the original array size.

    If you don’t know one of the values(like columns)

    array.reshape(rows, -1)

    NumPy will calculate the number of columns that fit.

In [79]:
# -1 in reshape --> Auto calculation 

# 1D to 2D
a = np.array([1,2,3,4,5,6])

print(a.reshape(-1,2))

[[1 2]
 [3 4]
 [5 6]]


In [80]:
# 1D to 3D 

a = np.array([10,20,30,40,50,60])

a


array([10, 20, 30, 40, 50, 60])

In [85]:
c = a.reshape(2,3,1) # --> 1 block 2 rows 3 columns

print(c)
print(c.shape)


# [
#     [
#         [1,2,3],
#         [4,5,6]

#     ]
# ]

[[[10]
  [20]
  [30]]

 [[40]
  [50]
  [60]]]
(2, 3, 1)


In [87]:
# 2D to 3D

a = np.array([[1,2,3],[4,5,6]])

b = a.reshape(2,1,3)

print(b)
print(b.shape)

[[[1 2 3]]

 [[4 5 6]]]
(2, 1, 3)


In [90]:
# 3D to 2D

a = np.array([
    [[10,20],
     [30,40]],
    [[50,60],
     [70,80]]
])


b = a.reshape(1,8)
print(b)
print(b.shape)

[[10 20 30 40 50 60 70 80]]
(1, 8)


## Concatenation :

## Concatenation :

To Combine(Join) two or more arrays along a specific axis - either row-wise or column-wise

    Syntax :
    
    np.concatenate((arr1,arr2),axis = 0 or 1)
    
    axis = 0  --> join vertically(row-wise)
    
    axis = 1  --> join horizontally(col-wise)

In [1]:
import numpy as np

In [2]:
a = [[1,2],[3,4]]

b = [[5,6],[7,8]]

print(a)
print(b)



[[1, 2], [3, 4]]
[[5, 6], [7, 8]]


In [3]:
# Row increased,Columns same
result = np.concatenate((a,b),axis = 0)

# Columns increased, rows same
another_result = np.concatenate((a,b),axis = 1)

print("***** Result ****** ")
print(result)


print("***** Another Result ****** ")
print(another_result)

***** Result ****** 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
***** Another Result ****** 
[[1 2 5 6]
 [3 4 7 8]]


## Transpose :
    Transposing means to swap rows and columns of the array

    Synatx :

        arr.T or arr.transpose()

        a[row][col] -> becomes a[col][row]

In [4]:
a = np.array([[1,2,3],
              [4,5,6]])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.shape(a)

(2, 3)

In [13]:
b = a.T
b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
np.shape(b)

(3, 2)

## Swapaxes :

    Used to **Swap any two axes** in a multi dimensional array.

    More Powerfull than transpose for 3D or Higher Dimensional arrays

    Syntax :

        np.swapaxes(arr,axis1,axis2)

        a[block][row][col]  -> a[row][block][col]

Axis numbering 0 la start aagum

    2D : 

        axis 0 = rows,
        axis 1 = columns

    3D : 

        axis 0 = first dim
        axis 1 = second
        axis 2 = third

        example :

            shape(2,3,4) 

            axis = 0 ,axis = 1 ,axis = 2

    2D Mapping rule :

        a[i,j] --> a[j,i]

    3D Mapping Rule : -> (2,3,4)

        swapaxes(b,0,2)
            
        b[i,j,k]  --> [c[k,j,i]]

        print(b[1,2,3], c[3,2,1])

In [25]:
arr = [
    [
        [10,20,30,40],
        [50,60,70,80],
        [1,2,3,4]
    ],
    [
        [11,22,33,44],
        [55,66,77,88],
        [23,13,43,53]
    ]
]

np.shape(arr)


(2, 3, 4)

In [26]:
arr

[[[10, 20, 30, 40], [50, 60, 70, 80], [1, 2, 3, 4]],
 [[11, 22, 33, 44], [55, 66, 77, 88], [23, 13, 43, 53]]]

In [33]:
swap = np.swapaxes(arr,0,-2)
swap

array([[[10, 20, 30, 40],
        [11, 22, 33, 44]],

       [[50, 60, 70, 80],
        [55, 66, 77, 88]],

       [[ 1,  2,  3,  4],
        [23, 13, 43, 53]]])

In [16]:
a = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(a)
print(a.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [15]:
swaped = np.swapaxes(a,0,1)
print(swaped)
print(swaped.shape)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
(2, 2, 2)


In [17]:
# 2D Examples :

arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.swapaxes(arr,1,-1)

array([[1, 2, 3],
       [4, 5, 6]])

## Array Split :

    Multiple smaller array ah split panrathu..
        
        1. np.split() :
        
            split array into equal parts
            
            Syntax :
                
                np.split(array,no_of_parts,axis)
                

In [34]:
# 1. Split rows equally :

a = np.array([[1,2],
             [3,4],
             [5,6],
             [7,8]])

a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [39]:
split_array = np.split(a,2,axis=1)

print(split_array)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


In [40]:
for part in split_array:
    print(part)

[[1]
 [3]
 [5]
 [7]]
[[2]
 [4]
 [6]
 [8]]


## 2. np.Array_split() :

    same as split() but is allows unequal split

    usefull when elements/rows can't divide equally

#### Syntax :

    np.array_split(array,no_of_parts,axis)

In [41]:
a = np.array([[1,2],
             [3,4],
             [5,6],
             [7,8],
             [9,10]])
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [49]:

result = np.array_split(a,2,axis=0)

print(result)

[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[ 7,  8],
       [ 9, 10]])]


## 3. np.hsplit() : -> Horizontal Split

    special case of split() - splits columns only

    axis = 1 fixed

    only for 2D arrays

    Syntax :
        np.hsplit(array,no_of_parts)

In [50]:
a = np.array([[1,2,3,4],
              [5,6,7,8]])

a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
result = np.hsplit(a,4)
result

[array([[1],
        [5]]),
 array([[2],
        [6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

## np.vsplit(): --> Vertical Split(Rows)

    - special case of split() - split rows only
    - axis-0 = fixed
    only for 2D arrays

#### Syntax :

    np.vsplit(array,no_of_parts)

In [54]:
a = np.array([[1,2],
              [3,4],
              [5,6],
              [7,8]])

a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [57]:
result = np.vsplit(a,4)
print(result)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


## np.dsplit() --> DepthSplit(for 3D Arrays)

- used only for 3D arrays
- splits along depth axis(axis = 2)

#### Syntax : 

    np.dsplit(array,no_of_parts)

In [65]:
a = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

np.shape(a)

(2, 2, 3)

In [64]:
result = np.dsplit(a,3)

result

[array([[[ 1],
         [ 4]],
 
        [[ 7],
         [10]]]),
 array([[[ 2],
         [ 5]],
 
        [[ 8],
         [11]]]),
 array([[[ 3],
         [ 6]],
 
        [[ 9],
         [12]]])]

In [67]:
np.shape(result)

(3, 2, 2, 1)

## Numpy Search Functions :

    to search or locate values inside arrays

### np.where() :

    Find index of elements matching a condition or replace values based on condition

#### Syntax :

    np.where(condition)
    
    **or**
    
    np.where(condtion,value_if_True,value_if_False)

In [69]:
# Find Where Elements > 10

arr = np.array([5,12,7,10,13,3,18])

result = np.where(arr <= 10)

result

(array([0, 2, 3, 5], dtype=int64),)

In [70]:
# Condition Basaed Replacement :

result = np.where(arr > 10 , 100 , 0)

result

array([  0, 100,   0,   0, 100,   0, 100])

In [73]:
#  Where in 3D :

arr = np.array([
    [[1,0],[3,0]],
    [[5,0],[0,8]]
])

np.shape(arr)

(2, 2, 2)

In [74]:
np.where(arr > 0)


(array([0, 0, 1, 1], dtype=int64),
 array([0, 1, 0, 1], dtype=int64),
 array([0, 0, 0, 1], dtype=int64))